[build]
  base    = "frontend"
  command = "npm run build"
  publish = "dist" # <--- THIS IS THE FIX

# This is your proxy rule (which is correct)
[[redirects]]
  from   = "/api/*"
  to     = "https://ecommerce-assignment-1o19.onrender.com/api/:splat"
  status = 200