# This tells Netlify which folder to build (your frontend app)
[build]
  base    = "frontend"
  command = "npm run build"
  publish = "frontend/dist"

# This is the proxy rule for Netlify (it's called a 'redirect')
# This does the exact same job as the vercel.json file
[[redirects]]
  from   = "/api/*"
  to     = "https://ecommerce-assignment-1o19.onrender.com/api/:splat"
  status = 200